AllCops:
  Documentation:
    Enabled: false
Metrics/LineLength:
  Max: 100
  Exclude:
    - 'db/schema.rb'
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
